# =============================================================================
# Plugins Manager
# =============================================================================
- repo: Shougo/dein.vim

- repo: wsdjeg/dein-ui.vim

- repo: Luk3Yao/spaceline.vim
  hook_add: let g:spaceline_seperate_style= 'slant-cons'

# =============================================================================
# Appearance & UI Elements & Animations
# =============================================================================
- repo: Luk3Yao/vim-gruvbox8

- repo: bagrat/vim-buffet
  hook_add: source $VIM_PATH/config/plugins/buffet.vim

- repo: ryanoasis/vim-devicons
  hook_add: let g:webdevicons_enable_denite = 1

- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source  $VIM_PATH/config/plugins/defx.vim

- repo: kristijanhusak/defx-git
  on_source: defx.nvim
  hook_source: source $VIM_PATH/config/plugins/defx-git.vim

- repo: kristijanhusak/defx-icons
  on_source: defx.nvim

- repo: majutsushi/tagbar
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_width = 40
    if executable('jsctags')
      let g:tagbar_type_javiascript = { 'ctagsbin': 'jsctags' }
    endif

- repo: kassio/neoterm

- repo: camspiers/animate.vim
  hook_add: source $VIM_PATH/config/plugins/animate.vim

- repo: camspiers/lens.vim
  hook_add: source $VIM_PATH/config/plugins/lens.vim

# =============================================================================
# Prompts
# =============================================================================
- repo: liuchengxu/vim-which-key
  on_cmd: [Whichkey, Whichkey!]
  hook_source: source  $VIM_PATH/config/plugins/whichkey.vim
  hook_post_source: |
        call which_key#register('<Space>', 'g:which_key_map')
        call which_key#register(';', 'g:which_key_localmap')
        call which_key#register(']', 'g:which_key_rsbgmap')
        call which_key#register('[', 'g:which_key_lsbgmap')

# =============================================================================
# Search & Motion
# =============================================================================
- repo: ludovicchabant/vim-gutentags
  if: executable('ctags')
  on_path: .*
  hook_add: source $VIM_PATH/config/plugins/vim-gutentags.vim

- repo: junegunn/fzf
  build: './install --all'
  merged: 0

- repo: junegunn/fzf.vim
  depends: fzf
  on_cmd: [Colors,Rg,Buffers]
  on_func: Fzf_dev
  hook_source: source $VIM_PATH/config/plugins/fzf.vim

# =============================================================================
# Completion
# =============================================================================
- repo: neoclide/coc.nvim
  merge: 0
  rev: release
  hook_add: source  $VIM_PATH/config/plugins/coc.vim
