# =============================================================================
# Plugins Manager
# =============================================================================
- repo: Shougo/dein.vim

- repo: wsdjeg/dein-ui.vim

- repo: glepnir/spaceline.vim
  hook_add: let g:spaceline_seperate_style= 'arrow'

# =============================================================================
# Appearance & UI Elements & Animations
# =============================================================================
- repo: bagrat/vim-buffet
  hook_add: source $VIM_PATH/config/plugins/buffet.vim

- repo: ryanoasis/vim-devicons
  hook_add: let g:webdevicons_enable_denite = 1

- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source $VIM_PATH/config/plugins/defx.vim

- repo: kristijanhusak/defx-git
  on_source: defx.nvim
  hook_source: source $VIM_PATH/config/plugins/defx-git.vim

- repo: kristijanhusak/defx-icons
  on_source: defx.nvim

- repo: majutsushi/tagbar
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_width = 40
    if executable('jsctags')
      let g:tagbar_type_javiascript = { 'ctagsbin': 'jsctags' }
    endif

- repo: kassio/neoterm

- repo: t9md/vim-choosewin
  on_map: { n: <Plug> }
  hook_source: source $VIM_PATH/config/plugins/vim-choosewin.vim

- repo: yuttie/comfortable-motion.vim
  on_func: comfortable_motion#flick
  hook_add: |
        let g:comfortable_motion_no_default_key_mappings = 1
        let g:comfortable_motion_impulse_multiplier = 1

- repo: rhysd/accelerated-jk
  on_map: { n: <Plug> }

- repo: liuchengxu/vim-which-key
  on_cmd: [Whichkey, Whichkey!]
  hook_source: source  $VIM_PATH/config/plugins/whichkey.vim
  hook_post_source: |
        call which_key#register('<Space>', 'g:which_key_map')
        call which_key#register(';', 'g:which_key_localmap')
        call which_key#register(']', 'g:which_key_rsbgmap')
        call which_key#register('[', 'g:which_key_lsbgmap')

# =============================================================================
# Prompts
# =============================================================================
- repo: liuchengxu/vim-which-key
  on_cmd: [Whichkey, Whichkey!]
  hook_source: source  $VIM_PATH/config/plugins/whichkey.vim
  hook_post_source: |
        call which_key#register('<Space>', 'g:which_key_map')
        call which_key#register(';', 'g:which_key_localmap')
        call which_key#register(']', 'g:which_key_rsbgmap')
        call which_key#register('[', 'g:which_key_lsbgmap')

# =============================================================================
# Search & Motion
# =============================================================================
# - repo: ludovicchabant/vim-gutentags
#   if: executable('ctags')
#   on_path: .*
#   hook_add: source $VIM_PATH/config/plugins/vim-gutentags.vim

- repo: junegunn/fzf
  build: './install --all'
  merged: 0

- repo: junegunn/fzf.vim
  depends: fzf
  on_cmd: [Colors,Rg,Buffers]
  on_func: Fzf_dev
  hook_source: source $VIM_PATH/config/plugins/fzf.vim

# =============================================================================
# Completion
# =============================================================================
- repo: neoclide/coc.nvim
  merge: 0
  rev: release
  hook_add: source  $VIM_PATH/config/plugins/coc.vim

