# =============================================================================
# Plugins Manager
# =============================================================================
- repo: Shougo/dein.vim

- repo: wsdjeg/dein-ui.vim

- repo: Luk3Yao/spaceline.vim
  hook_add: let g:spaceline_seperate_style= 'none'

# =============================================================================
# Appearance & UI Elements & Animations
# =============================================================================
- repo: Luk3Yao/vim-gruvbox8

- repo: bagrat/vim-buffet
  hook_add: source $VIM_PATH/config/plugins/buffet.vim

- repo: ryanoasis/vim-devicons
  hook_add: let g:webdevicons_enable_denite = 1

- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source  $VIM_PATH/config/plugins/defx.vim

- repo: kristijanhusak/defx-git
  on_source: defx.nvim
  hook_source: source $VIM_PATH/config/plugins/defx-git.vim

- repo: kristijanhusak/defx-icons
  on_source: defx.nvim

- repo: majutsushi/tagbar
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_width = 40
    if executable('jsctags')
      let g:tagbar_type_javiascript = { 'ctagsbin': 'jsctags' }
    endif

# =============================================================================
# Prompts
# =============================================================================
- repo: liuchengxu/vim-which-key
  on_cmd: [Whichkey, Whichkey!]
  hook_source: source  $VIM_PATH/config/plugins/whichkey.vim
  hook_post_source: |
        call which_key#register('<Space>', 'g:which_key_map')
        call which_key#register(';', 'g:which_key_localmap')
        call which_key#register(']', 'g:which_key_rsbgmap')
        call which_key#register('[', 'g:which_key_lsbgmap')

# =============================================================================
# Search & Motion
# =============================================================================
- repo: ludovicchabant/vim-gutentags
  if: executable('ctags')
  on_path: .*
  hook_add: source $VIM_PATH/config/plugins/vim-gutentags.vim

# =============================================================================
# Completion
# =============================================================================
- repo: neoclide/coc.nvim
  merge: 0
  rev: release
  hook_add: source  $VIM_PATH/config/plugins/coc.vim
